default: &default
  # audio.kitatdot.net 
  audio_url: http://playz.duckdns.org:19003
  # image.kitatdot.net 
  image_url: http://playz.duckdns.org:19002
  # images.kitatdot.net 
  images_url: http://playz.duckdns.org:19001
  # albumart.kitatdot.net 
  albumart_url: http://playz.duckdns.org:19004
  
development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
