production:
  solr:
    hostname: localhost
    port: 8080
    log_level: WARNING
    path: /solr/production
    # read_timeout: 2
    # open_timeout: 0.5

development:
  solr:
    hostname: kitatdotnet.net
    port: 8080
    log_level: WARNING
    path: /solr/production

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING
    path: /solr/test
    